### ISSUE TITLE
EPIC: DB Migration

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#614]
- [ ] TASK: Integrate Kysely https://github.com/kysely-org/kysely
- [ ] STORY: create a migration script from mongoDB -> postgres (remap seeder jsons)
- [ ] STORY:  refactor repositories 
- [ ] STORY: refactor controllers
- [ ] STORY: refactor views and react components

**Comment by stacysealky** [comment]
I added a new boolean field called 'hasArtImage' to the WishCard.
If the child's image is their art image, hasArtImage = true
It shows the art badge on their wish card image.

<img width="1108" alt="Screenshot 2023-11-29 at 11 16 25 PM" src="https://github.com/donategifts/donategifts/assets/26069780/502ff638-2234-4d66-9636-983cda94a1b1">

<img width="319" alt="Screenshot 2023-11-29 at 11 16 42 PM" src="https://github.com/donategifts/donategifts/assets/26069780/2d2faa48-0b9a-40b6-9653-d89762f29d24">
