### ISSUE TITLE
EPIC: Agency Enhancements

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#633]
Agency users need to start creating wish cards in September. 
Deadline: September 15, 2023 

- [ ] STORY: "Create a Wish Card" page - UI redesign, review validation rules
- [ ] STORY: "Create a Wish Card" page - default shipping address toggle 
- [ ] STORY: "Create a Wish Card" page - item image uploader
- [ ] TASK: Wish page should show the item image if exists, else show placeholder
- [ ] STORY: image slider carousel for wish card image and item image on each card view
- [ ] STORY: Automate all agency related emails (wish card published, item delivered, message received)
- [ ] STORY: "Manage Wish Cards" -  UI redesign
- [ ] STORY: "Manage Wish Cards" -  show donation stats (total $, total num donations, total num donors)
- [ ] STORY: separate My Agency and My Account from profile
- [ ] STORY: My Agency page logo uploader 
- [ ] STORY: Agency Sign Up page logo uploader 

Can be developed after September
- [ ] BACKLOG: "Manage Wish Cards" -  Donated wishcards show donor user first name and post message icon
- [ ] BACKLOG: "Manage Wish Cards" - Post public thank you message for donor (email alert to donor, publish in communtiy page) 
- [ ] BACKLOG: "My Agency" page has a public view link
- [ ] BACKLOG: My Agency public view page UI

**Comment by stacysealky** [comment]
hide social logins until fixed
